apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: "DB_HOST"
  DB_PORT: "DB_PORT"
  DB_USERNAME: "DB_USERNAME"
  QUESTION_DB_URL: "DATABASE_URL"
  QUIZ_DB_URL: "DATABASE_URL"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_PASSWORD: "YOUR_DB_PASSWORD"


